<?php

use Illuminate\Database\Seeder;

class SeoConfigsTableSeeder extends Seeder
{

  const TABLE_NAME = 'seo_configs';
  const FIELD_SLUG = 'slug';
  const FIELD_DESCRIPTION = 'description';
  const FIELD_TITLE = 'title';
  const FIELD_CANONICAL_URL = 'canonical_url';
  const FIELD_OG_TITLE = 'og_title';
  const FIELD_OG_TYPE = 'og_type';
  const FIELD_OG_IMAGE = 'og_image';
  const FIELD_OG_URL = 'og_url';
  const FIELD_OG_DESCRIPTION = 'og_description';
  const FIELD_TWITTER_CARD = 'twitter_card';
  const FIELD_TWITTER_SITE = 'twitter_site';

  const VALUE_OG_TYPE = 'website';
  const VALUE_TWITTER_CARD = 'summary';
  const VALUE_TWITTER_SITE = '@anhqvstats';

  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    $seoConfigs = $this->getSeoConfigs();

    foreach ($seoConfigs as $seoConfig) {
      DB::table(static::TABLE_NAME)->insert([
        static::FIELD_SLUG => $seoConfig[static::FIELD_SLUG],
        static::FIELD_TITLE => $seoConfig[static::FIELD_TITLE],
        static::FIELD_DESCRIPTION => $seoConfig[static::FIELD_DESCRIPTION],
        static::FIELD_CANONICAL_URL => $seoConfig[static::FIELD_CANONICAL_URL],static::FIELD_OG_TITLE => $seoConfig[static::FIELD_OG_TITLE],
        static::FIELD_OG_TYPE => $seoConfig[static::FIELD_OG_TYPE],
        static::FIELD_OG_IMAGE => $seoConfig[static::FIELD_OG_IMAGE],
        static::FIELD_OG_URL => $seoConfig[static::FIELD_OG_URL],
        static::FIELD_OG_DESCRIPTION => $seoConfig[static::FIELD_OG_DESCRIPTION],
        static::FIELD_TWITTER_CARD => $seoConfig[static::FIELD_TWITTER_CARD],
        static::FIELD_TWITTER_SITE => $seoConfig[static::FIELD_TWITTER_SITE],
      ]);
    }
  }

  public function getSeoConfigs()
  {
    return [
      [
        static::FIELD_SLUG => 'home',
        static::FIELD_TITLE => 'ANHQV STATS',
        static::FIELD_DESCRIPTION => 'Información y estadísticas Aquí No Hay Quien Viva: personajes, actores, capítulos... y mucho más. ✅ Disponible API REST documentada.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/',static::FIELD_OG_TITLE => 'ANHQV STATS',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/logo.png',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/',
        static::FIELD_OG_DESCRIPTION => 'Información y estadísticas Aquí No Hay Quien Viva: personajes, actores, capítulos... y mucho más. ✅ Disponible API REST documentada.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'characters',
        static::FIELD_TITLE => 'Personajes',
        static::FIELD_DESCRIPTION => 'Galería con todos los personajes que aparecen en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes',
        static::FIELD_OG_TITLE => 'Personajes',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/logo.png',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes',
        static::FIELD_OG_DESCRIPTION => 'Galería con los personajes que han participado en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-marisa-benito',
        static::FIELD_TITLE => 'Personaje | Marisa Benito',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Marisa Benito, personaje de Aquí No Hay Quien Viva interpretado por Mariví Bilbao.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/marisa-benito',
        static::FIELD_OG_TITLE => 'Personaje | Marisa Benito',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/marisa-benito.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/marisa-benito',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Marisa Benito, personaje de Aquí No Hay Quien Viva interpretado por Mariví Bilbao.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-vicenta-benito',
        static::FIELD_TITLE => 'Personaje | Vicenta Benito',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Vicenta Benito, personaje de Aquí No Hay Quien Viva interpretado por Gemma Cuervo.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/vicenta-benito',
        static::FIELD_OG_TITLE => 'Personaje | Vicenta Benito',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/vicenta-benito.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/vicenta-benito',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Vicenta Benito, personaje de Aquí No Hay Quien Viva interpretado por Gemma Cuervo.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-juan-cuesta',
        static::FIELD_TITLE => 'Personaje | Juan Cuesta',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Juan Cuesta, personaje de Aquí No Hay Quien Viva interpretado por José Luis Gil.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/juan-cuesta',
        static::FIELD_OG_TITLE => 'Personaje | Juan Cuesta',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/juan-cuesta.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/juan-cuesta',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Juan Cuesta, personaje de Aquí No Hay Quien Viva interpretado por José Luis Gil.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-paloma-hurtado',
        static::FIELD_TITLE => 'Personaje | Paloma Hurtado',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Paloma Hurtado, personaje de Aquí No Hay Quien Viva interpretado por Loles León.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/paloma-hurtado',
        static::FIELD_OG_TITLE => 'Personaje | Paloma Hurtado',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/paloma-hurtado.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/paloma-hurtado',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Paloma Hurtado, personaje de Aquí No Hay Quien Viva interpretado por Loles León.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-jose-miguel-cuesta',
        static::FIELD_TITLE => 'Personaje | José Miguel Cuesta',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de José Miguel Cuesta, personaje de Aquí No Hay Quien Viva interpretado por Edu García.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/jose-miguel-cuesta',
        static::FIELD_OG_TITLE => 'Personaje | José Miguel Cuesta',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/jose-miguel-cuesta.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/jose-miguel-cuesta',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de José Miguel Cuesta, personaje de Aquí No Hay Quien Viva interpretado por Edu García.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-belen-lopez',
        static::FIELD_TITLE => 'Personaje | Belén López',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Belén López, personaje de Aquí No Hay Quien Viva interpretado por Malena Alterio.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/belen-lopez',
        static::FIELD_OG_TITLE => 'Personaje | Belén López',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/belen-lopez.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/belen-lopez',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Belén López, personaje de Aquí No Hay Quien Viva interpretado por Malena Alterio.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-alicia-sanz',
        static::FIELD_TITLE => 'Personaje | Alicia Sanz',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Alicia Sanz, personaje de Aquí No Hay Quien Viva interpretado por Laura Pamplona.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/alicia-sanz',
        static::FIELD_OG_TITLE => 'Personaje | Alicia Sanz',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/alicia-sanz.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/alicia-sanz',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Alicia Sanz, personaje de Aquí No Hay Quien Viva interpretado por Laura Pamplona.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-concha',
        static::FIELD_TITLE => 'Personaje | Concha',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Concha, personaje de Aquí No Hay Quien Viva interpretado por Emma Penella.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/concha',
        static::FIELD_OG_TITLE => 'Personaje | Concha',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/concha.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/concha',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Concha, personaje de Aquí No Hay Quien Viva interpretado por Emma Penella.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-dani-rubio',
        static::FIELD_TITLE => 'Personaje | Dani Rubio',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Dani Rubio, personaje de Aquí No Hay Quien Viva interpretado por Dani Ballesteros.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/dani-rubio',
        static::FIELD_OG_TITLE => 'Personaje | Dani Rubio',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/dani-rubio.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/dani-rubio',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Dani Rubio, personaje de Aquí No Hay Quien Viva interpretado por Dani Ballesteros.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-armando',
        static::FIELD_TITLE => 'Personaje | Armando',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Armando, personaje de Aquí No Hay Quien Viva interpretado por Joseba Apaolaza.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/armando',
        static::FIELD_OG_TITLE => 'Personaje | Armando',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/armando.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/armando',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Armando, personaje de Aquí No Hay Quien Viva interpretado por Joseba Apaolaza.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-mauricio-hidalgo',
        static::FIELD_TITLE => 'Personaje | Mauricio Hidalgo',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Mauricio Hidalgo, personaje de Aquí No Hay Quien Viva interpretado por Luis Merlo.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/mauricio-hidalgo',
        static::FIELD_OG_TITLE => 'Personaje | Mauricio Hidalgo',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/mauricio-hidalgo.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/mauricio-hidalgo',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Mauricio Hidalgo, personaje de Aquí No Hay Quien Viva interpretado por Luis Merlo.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-fernando-navarro',
        static::FIELD_TITLE => 'Personaje | Fernando Navarro',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Fernando Navarro, personaje de Aquí No Hay Quien Viva interpretado por Adriá Collado.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/fernando-navarro',
        static::FIELD_OG_TITLE => 'Personaje | Fernando Navarro',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/fernando-navarro.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/fernando-navarro',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Fernando Navarro, personaje de Aquí No Hay Quien Viva interpretado por Adriá Collado.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-natalia-cuesta',
        static::FIELD_TITLE => 'Personaje | Natalia Cuesta',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Natalia Cuesta, personaje de Aquí No Hay Quien Viva interpretado por Sofía Nieto.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/natalia-cuesta',
        static::FIELD_OG_TITLE => 'Personaje | Natalia Cuesta',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/natalia-cuesta.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/natalia-cuesta',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Natalia Cuesta, personaje de Aquí No Hay Quien Viva interpretado por Sofía Nieto.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-roberto-alonso',
        static::FIELD_TITLE => 'Personaje | Roberto Alonso',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Roberto Alonso, personaje de Aquí No Hay Quien Viva interpretado por Daniel Guzmán.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/roberto-alonso',
        static::FIELD_OG_TITLE => 'Personaje | Roberto Alonso',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/roberto-alonso.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/roberto-alonso',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Roberto Alonso, personaje de Aquí No Hay Quien Viva interpretado por Daniel Guzmán.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-lucia-alvarez',
        static::FIELD_TITLE => 'Personaje | Lucía Álvarez',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Lucía Álvarez, personaje de Aquí No Hay Quien Viva interpretado por María Adánez.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/lucia-alvarez',
        static::FIELD_OG_TITLE => 'Personaje | Lucía Álvarez',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/lucia-alvarez.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/lucia-alvarez',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Lucía Álvarez, personaje de Aquí No Hay Quien Viva interpretado por María Adánez.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-emilio-delgado',
        static::FIELD_TITLE => 'Personaje | Emilio Delgado',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Emilio Delgado, personaje de Aquí No Hay Quien Viva interpretado por Fernando Tejero.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/emilio-delgado',
        static::FIELD_OG_TITLE => 'Personaje | Emilio Delgado',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/emilio-delgado.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/emilio-delgado',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Emilio Delgado, personaje de Aquí No Hay Quien Viva interpretado por Fernando Tejero.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-mozo-mudanza-1',
        static::FIELD_TITLE => 'Personaje | Mozo Mudanza 1',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Mozo Mudanza 1, personaje de Aquí No Hay Quien Viva interpretado por Antonio Gómez.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/mozo-mudanza-1',
        static::FIELD_OG_TITLE => 'Personaje | Mozo Mudanza 1',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/mozo-mudanza-1.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/mozo-mudanza-1',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Mozo Mudanza 1, personaje de Aquí No Hay Quien Viva interpretado por Antonio Gómez.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-mozo-mudanza-2',
        static::FIELD_TITLE => 'Personaje | Mozo Mudanza 2',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Mozo Mudanza 2, personaje de Aquí No Hay Quien Viva interpretado por Arsenio Luna.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/mozo-mudanza-2',
        static::FIELD_OG_TITLE => 'Personaje | Mozo Mudanza 2',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/mozo-mudanza-2.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/mozo-mudanza-2',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Mozo Mudanza 2, personaje de Aquí No Hay Quien Viva interpretado por Arsenio Luna.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-repartidor-propaganda',
        static::FIELD_TITLE => 'Personaje | Repartidor Propaganda',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del Repartidor de Propaganda, personaje extra de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/repartidor-propaganda',
        static::FIELD_OG_TITLE => 'Personaje | Repartidor Propaganda',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/repartidor-propaganda.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/repartidor-propaganda',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del Repartidor de Propaganda, personaje extra de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-paco',
        static::FIELD_TITLE => 'Personaje | Paco',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Paco, personaje de Aquí No Hay Quien Viva interpretado por Guillermo Ortega.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/paco',
        static::FIELD_OG_TITLE => 'Personaje | Paco',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/paco.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/paco',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Paco, personaje de Aquí No Hay Quien Viva interpretado por Guillermo Ortega.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-santiago-segura',
        static::FIELD_TITLE => 'Personaje | Santiago Segura',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Santiago Segura, personaje de Aquí No Hay Quien Viva interpretado por él mismo.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/santiago-segura',
        static::FIELD_OG_TITLE => 'Personaje | Santiago Segura',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/santiago-segura.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/santiago-segura',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Santiago Segura, personaje de Aquí No Hay Quien Viva interpretado por él mismo.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-mariano-delgado',
        static::FIELD_TITLE => 'Personaje | Mariano Delgado',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Mariano Delgado, personaje de Aquí No Hay Quien Viva interpretado por Eduardo Gómez.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/mariano-delgado',
        static::FIELD_OG_TITLE => 'Personaje | Mariano Delgado',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/mariano-delgado.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/mariano-delgado',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Mariano Delgado, personaje de Aquí No Hay Quien Viva interpretado por Eduardo Gómez.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'character-esther',
        static::FIELD_TITLE => 'Personaje | Esther',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Esther, personaje de Aquí No Hay Quien Viva interpretado por Susana Reija.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/personajes/esther',
        static::FIELD_OG_TITLE => 'Personaje | Esther',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/characters/esther.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/personajes/esther',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Esther, personaje de Aquí No Hay Quien Viva interpretado por Susana Reija.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actors',
        static::FIELD_TITLE => 'Actores',
        static::FIELD_DESCRIPTION => 'Galería con todos los actores que intervienen en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores',
        static::FIELD_OG_TITLE => 'Actores',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/logo.png',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores',
        static::FIELD_OG_DESCRIPTION => 'Galería con todos los actores que intervienen en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actor-marivi-bilbao',
        static::FIELD_TITLE => 'Actor | Mariví Bilbao',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Mariví Bilbao, actriz que da vida a Marisa Benito en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores/marivi-bilbao',
        static::FIELD_OG_TITLE => 'Actor | Mariví Bilbao',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/actors/marivi-bilbao.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores/marivi-bilbao',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Mariví Bilbao, actriz que da vida a Marisa Benito en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actor-gemma-cuervo',
        static::FIELD_TITLE => 'Actor | Gemma Cuervo',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Gemma Cuervo, actriz que da vida a Vicenta Benito en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores/gemma-cuervo',
        static::FIELD_OG_TITLE => 'Actor | Gemma Cuervo',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/actors/gemma-cuervo.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores/gemma-cuervo',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Gemma Cuervo, actriz que da vida a Vicenta Benito en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actor-jose-luis-gil',
        static::FIELD_TITLE => 'Actor | José Luis Gil',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de José Luis Gil, actor que da vida a Juan Cuesta en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores/jose-luis-gil',
        static::FIELD_OG_TITLE => 'Actor | José Luis Gil',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/actors/jose-luis-gil.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores/jose-luis-gil',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de José Luis Gil, actor que da vida a Juan Cuesta en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actor-loles-leon',
        static::FIELD_TITLE => 'Actor | Loles León',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Loles León, actriz que da vida a Paloma Hurtado en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores/loles-leon',
        static::FIELD_OG_TITLE => 'Actor | Loles León',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/actors/loles-leon.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores/loles-leon',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Loles León, actriz que da vida a Paloma Hurtado en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actor-edu-garcia',
        static::FIELD_TITLE => 'Actor | Edu García',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Edu García, actor que da vida a José Miguel Cuesta en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores/edu-garcia',
        static::FIELD_OG_TITLE => 'Actor | Edu García',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/actors/edu-garcia.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores/edu-garcia',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Edu García, actor que da vida a José Miguel Cuesta en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actor-malena-alterio',
        static::FIELD_TITLE => 'Actor | Malena Alterio',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Malena Alterio, actriz que da vida a Belén López en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores/malena-alterio',
        static::FIELD_OG_TITLE => 'Actor | Malena Alterio',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/actors/malena-alterio.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores/malena-alterio',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Malena Alterio, actriz que da vida a Belén López en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actor-laura-pamplona',
        static::FIELD_TITLE => 'Actor | Laura Pamplona',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Laura Pamplona, actriz que da vida a Alicia Sanz en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores/laura-pamplona',
        static::FIELD_OG_TITLE => 'Actor | Laura Pamplona',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/actors/laura-pamplona.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores/laura-pamplona',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Laura Pamplona, actriz que da vida a Alicia Sanz en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actor-emma-penella',
        static::FIELD_TITLE => 'Actor | Emma Penella',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Emma Penella, actriz que da vida a Concha en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores/emma-penella',
        static::FIELD_OG_TITLE => 'Actor | Emma Penella',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/actors/emma-penella.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores/emma-penella',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Emma Penella, actriz que da vida a Concha en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actor-dani-ballesteros',
        static::FIELD_TITLE => 'Actor | Dani Ballesteros',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Dani Ballesteros, actor que da vida a Dani Rubio en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores/dani-ballesteros',
        static::FIELD_OG_TITLE => 'Actor | Dani Ballesteros',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/actors/dani-ballesteros.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores/dani-ballesteros',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Dani Ballesteros, actor que da vida a Dani Rubio en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actor-joseba-apaolaza',
        static::FIELD_TITLE => 'Actor | Joseba Apaolaza',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Joseba Apaolaza, actor que da vida a Armando en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores/joseba-apaolaza',
        static::FIELD_OG_TITLE => 'Actor | Joseba Apaolaza',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/actors/joseba-apaolaza.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores/joseba-apaolaza',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Joseba Apaolaza, actor que da vida a Armando en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actor-luis-merlo',
        static::FIELD_TITLE => 'Actor | Luis Merlo',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Luis Merlo, actor que da vida a Mauricio Hidalgo en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores/luis-merlo',
        static::FIELD_OG_TITLE => 'Actor | Luis Merlo',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/actors/luis-merlo.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores/luis-merlo',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Luis Merlo, actor que da vida a Mauricio Hidalgo en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actor-adria-collado',
        static::FIELD_TITLE => 'Actor | Adriá Collado',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Adriá Collado, actor que da vida a Fernando Navarro en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores/adria-collado',
        static::FIELD_OG_TITLE => 'Actor | Adriá Collado',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/actors/adria-collado.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores/adria-collado',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Adriá Collado, actor que da vida a Fernando Navarro en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actor-sofia-nieto',
        static::FIELD_TITLE => 'Actor | Sofía Nieto',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Sofía Nieto, actriz que da vida a Natalia Cuesta en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores/sofia-nieto',
        static::FIELD_OG_TITLE => 'Actor | Sofía Nieto',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/actors/sofia-nieto.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores/sofia-nieto',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Sofía Nieto, actriz que da vida a Natalia Cuesta en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actor-daniel-guzman',
        static::FIELD_TITLE => 'Actor | Daniel Guzmán',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Daniel Guzmán, actor que da vida a Roberto Alonso en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores/daniel-guzman',
        static::FIELD_OG_TITLE => 'Actor | Daniel Guzmán',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/actors/daniel-guzman.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores/daniel-guzman',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Daniel Guzmán, actor que da vida a Roberto Alonso en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actor-maria-adanez',
        static::FIELD_TITLE => 'Actor | María Adánez',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de María Adánez, actriz que da vida a Lucía Álvarez en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores/maria-adanez',
        static::FIELD_OG_TITLE => 'Actor | María Adánez',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/actors/maria-adanez.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores/maria-adanez',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de María Adánez, actriz que da vida a Lucía Álvarez en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actor-fernando-tejero',
        static::FIELD_TITLE => 'Actor | Fernando Tejero',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Fernando Tejero, actor que da vida a Emilio Delgado en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores/fernando-tejero',
        static::FIELD_OG_TITLE => 'Actor | Fernando Tejero',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/actors/fernando-tejero.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores/fernando-tejero',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Fernando Tejero, actor que da vida a Emilio Delgado en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actor-antonio-gomez',
        static::FIELD_TITLE => 'Actor | Antonio Gómez',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Antonio Gómez, actor que da vida al Mozo de Mudanza 1 en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores/antonio-gomez',
        static::FIELD_OG_TITLE => 'Actor | Antonio Gómez',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/actors/antonio-gomez.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores/antonio-gomez',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Antonio Gómez, actor que da vida al Mozo de Mudanza 1 en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actor-arsenio-luna',
        static::FIELD_TITLE => 'Actor | Arsenio Luna',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Arsenio Luna, actor que da vida al Mozo de Mudanza 2 en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores/arsenio-luna',
        static::FIELD_OG_TITLE => 'Actor | Arsenio Luna',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/actors/desconocido.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores/arsenio-luna',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Arsenio Luna, actor que da vida al Mozo de Mudanza 2 en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actor-guillermo-ortega',
        static::FIELD_TITLE => 'Actor | Guillermo Ortega',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Guillermo Ortega, actor que da vida a Paco en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores/guillermo-ortega',
        static::FIELD_OG_TITLE => 'Actor | Guillermo Ortega',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/actors/guillermo-ortega.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores/guillermo-ortega',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Guillermo Ortega, actor que da vida a Paco en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actor-santiago-segura',
        static::FIELD_TITLE => 'Actor | Santiago Segura',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Santiago Segura, actor que se interpreta a sí mismo en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores/santiago-segura',
        static::FIELD_OG_TITLE => 'Actor | Santiago Segura',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/actors/santiago-segura.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores/santiago-segura',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Santiago Segura, actor que se interpreta a sí mismo en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actor-eduardo-gomez',
        static::FIELD_TITLE => 'Actor | Eduardo Gómez',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Eduardo Gómez, actor que da vida a Mariano Delgado en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores/eduardo-gomez',
        static::FIELD_OG_TITLE => 'Actor | Eduardo Gómez',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/actors/eduardo-gomez.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores/eduardo-gomez',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Eduardo Gómez, actor que da vida a Mariano Delgado en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'actor-susana-reija',
        static::FIELD_TITLE => 'Actor | Susana Reija',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles de Susana Reija, actriz que da vida a Esther en Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/actores/susana-reija',
        static::FIELD_OG_TITLE => 'Actor | Susana Reija',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/actors/desconocido.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/actores/susana-reija',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles de Susana Reija, actriz que da vida a Esther en Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'season-1-chapters',
        static::FIELD_TITLE => 'Temporada 1 | Capítulos',
        static::FIELD_DESCRIPTION => 'Galería con todos los capítulos de la primera temporada de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/1',
        static::FIELD_OG_TITLE => 'Temporada 1 | Capítulos',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/logo.png',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/1',
        static::FIELD_OG_DESCRIPTION => 'Galería con todos los capítulos de la primera temporada de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '1x01-erase-una-mudanza',
        static::FIELD_TITLE => '1x01 | Érase una mudanza',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 1x01 (Érase una mudanza) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x01-erase-una-mudanza',
        static::FIELD_OG_TITLE => '1x01 | Érase una mudanza',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/1x01.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x01-erase-una-mudanza',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 1x01 (Érase una mudanza) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '1x02-erase-una-reforma',
        static::FIELD_TITLE => '1x02 | Érase una reforma',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 1x02 (Érase una reforma) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x02-erase-una-reforma',
        static::FIELD_OG_TITLE => '1x02 | Érase una reforma',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/1x02.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x02-erase-una-reforma',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 1x02 (Érase una reforma) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '1x03-erase-el-reciclaje',
        static::FIELD_TITLE => '1x03 | Érase el reciclaje',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 1x03 (Érase el reciclaje) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x03-erase-el-reciclaje',
        static::FIELD_OG_TITLE => '1x03 | Érase el reciclaje',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/1x03.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x03-erase-el-reciclaje',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 1x03 (Érase el reciclaje) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '1x04-erase-un-rumor',
        static::FIELD_TITLE => '1x04 | Érase un rumor',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 1x04 (Érase un rumor) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x04-erase-un-rumor',
        static::FIELD_OG_TITLE => '1x04 | Érase un rumor',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/1x04.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x04-erase-un-rumor',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 1x04 (Érase un rumor) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '1x05-erase-un-nino',
        static::FIELD_TITLE => '1x05 | Érase un niño',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 1x05 (Érase un niño) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x05-erase-un-nino',
        static::FIELD_OG_TITLE => '1x05 | Érase un niño',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/1x05.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x05-erase-un-nino',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 1x05 (Érase un niño) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '1x06-erase-un-resbalon',
        static::FIELD_TITLE => '1x06 | Érase un resbalón',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 1x06 (Érase un resbalón) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x06-erase-un-resbalon',
        static::FIELD_OG_TITLE => '1x06 | Érase un resbalón',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/1x06.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x06-erase-un-resbalon',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 1x06 (Érase un resbalón) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '1x07-erase-una-rata',
        static::FIELD_TITLE => '1x07 | Érase una rata',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 1x07 (Érase una rata) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x07-erase-una-rata',
        static::FIELD_OG_TITLE => '1x07 | Érase una rata',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/1x07.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x07-erase-una-rata',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 1x07 (Érase una rata) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '1x08-erase-un-indigente',
        static::FIELD_TITLE => '1x08 | Érase un indigente',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 1x08 (Érase un indigente) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x08-erase-un-indigente',
        static::FIELD_OG_TITLE => '1x08 | Érase un indigente',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/1x08.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x08-erase-un-indigente',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 1x08 (Érase un indigente) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '1x09-erase-una-de-miedo',
        static::FIELD_TITLE => '1x09 | Érase una de miedo',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 1x09 (Érase una de miedo) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x09-erase-una-de-miedo',
        static::FIELD_OG_TITLE => '1x09 | Érase una de miedo',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/1x09.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x09-erase-una-de-miedo',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 1x09 (Érase una de miedo) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '1x10-erase-un-dilema',
        static::FIELD_TITLE => '1x10 | Érase un dilema',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 1x10 (Érase un dilema) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x10-erase-un-dilema',
        static::FIELD_OG_TITLE => '1x10 | Érase un dilema',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/1x10.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x10-erase-un-dilema',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 1x10 (Érase un dilema) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '1x11-erase-un-traspaso',
        static::FIELD_TITLE => '1x11 | Érase un traspaso',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 1x11 (Érase un traspaso) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x11-erase-un-traspaso',
        static::FIELD_OG_TITLE => '1x11 | Érase un traspaso',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/1x11.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x11-erase-un-traspaso',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 1x11 (Érase un traspaso) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '1x12-erase-un-sustituto',
        static::FIELD_TITLE => '1x12 | Érase un sustituto',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 1x12 (Érase un sustituto) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x12-erase-un-sustituto',
        static::FIELD_OG_TITLE => '1x12 | Érase un sustituto',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/1x12.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x12-erase-un-sustituto',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 1x12 (Érase un sustituto) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '1x13-erase-una-fiesta',
        static::FIELD_TITLE => '1x13 | Érase una fiesta',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 1x13 (Érase una fiesta) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x13-erase-una-fiesta',
        static::FIELD_OG_TITLE => '1x13 | Érase una fiesta',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/1x13.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x13-erase-una-fiesta',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 1x13 (Érase una fiesta) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '1x14-erase-una-averia',
        static::FIELD_TITLE => '1x14 | Érase una avería',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 1x14 (Érase una avería) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x14-erase-una-averia',
        static::FIELD_OG_TITLE => '1x14 | Érase una avería',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/1x14.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x14-erase-una-averia',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 1x14 (Érase una avería) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '1x15-erase-un-anillo',
        static::FIELD_TITLE => '1x15 | Érase un anillo',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 1x15 (Érase un anillo) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x15-erase-un-anillo',
        static::FIELD_OG_TITLE => '1x15 | Érase un anillo',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/1x15.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x15-erase-un-anillo',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 1x15 (Érase un anillo) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '1x16-erase-una-nochebuena',
        static::FIELD_TITLE => '1x16 | Érase una Nochebuena',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 1x16 (Érase una Nochebuena) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x16-erase-una-nochebuena',
        static::FIELD_OG_TITLE => '1x16 | Érase una Nochebuena',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/1x16.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x16-erase-una-nochebuena',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 1x16 (Érase una Nochebuena) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '1x17-erase-un-fin-de-ano',
        static::FIELD_TITLE => '1x17 | Érase un fin de año',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 1x17 (Érase un fin de año) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x17-erase-un-fin-de-ano',
        static::FIELD_OG_TITLE => '1x17 | Érase un fin de año',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/1x17.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/1/capitulos/1x17-erase-un-fin-de-ano',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 1x17 (Érase un fin de año) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'season-2-chapters',
        static::FIELD_TITLE => 'Temporada 2 | Capítulos',
        static::FIELD_DESCRIPTION => 'Galería con todos los capítulos de la segunda temporada de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/2',
        static::FIELD_OG_TITLE => 'Temporada 2 | Capítulos',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/logo.png',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/2',
        static::FIELD_OG_DESCRIPTION => 'Galería con todos los capítulos de la segunda temporada de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '2x01-erase-una-derrama',
        static::FIELD_TITLE => '2x01 | Érase una derrama',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 2x01 (Érase una derrama) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/2/capitulos/2x01-erase-una-derrama',
        static::FIELD_OG_TITLE => '2x01 | Érase una derrama',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/2x01.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/2/capitulos/2x01-erase-una-derrama',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 2x01 (Érase una derrama) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '2x02-erase-un-sueno-erotico',
        static::FIELD_TITLE => '2x02 | Érase un sueño erótico',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 2x02 (Érase un sueño erótico) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/2/capitulos/2x02-erase-un-sueno-erotico',
        static::FIELD_OG_TITLE => '2x02 | Érase un sueño erótico',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/2x02.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/2/capitulos/2x02-erase-un-sueno-erotico',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 2x02 (Érase un sueño erótico) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '2x03-erase-un-negocio',
        static::FIELD_TITLE => '2x03 | Érase un negocio',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 2x03 (Érase un negocio) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/2/capitulos/2x03-erase-un-negocio',
        static::FIELD_OG_TITLE => '2x03 | Érase un negocio',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/2x03.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/2/capitulos/2x03-erase-un-negocio',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 2x03 (Érase un negocio) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '2x04-erase-un-desafio',
        static::FIELD_TITLE => '2x04 | Érase un desafío',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 2x04 (Érase un desafío) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/2/capitulos/2x04-erase-un-desafio',
        static::FIELD_OG_TITLE => '2x04 | Érase un desafío',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/2x04.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/2/capitulos/2x04-erase-un-desafio',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 2x04 (Érase un desafío) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '2x05-erase-una-patrulla-ciudadana',
        static::FIELD_TITLE => '2x05 | Érase una patrulla ciudadana',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 2x05 (Érase una patrulla ciudadana) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/2/capitulos/2x05-erase-una-patrulla-ciudadana',
        static::FIELD_OG_TITLE => '2x05 | Érase una patrulla ciudadana',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/2x05.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/2/capitulos/2x05-erase-una-patrulla-ciudadana',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 2x05 (Érase una patrulla ciudadana) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '2x06-erase-un-rastrillo',
        static::FIELD_TITLE => '2x06 | Érase un rastrillo',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 2x06 (Érase un rastrillo) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/2/capitulos/2x06-erase-un-rastrillo',
        static::FIELD_OG_TITLE => '2x06 | Érase un rastrillo',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/2x06.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/2/capitulos/2x06-erase-un-rastrillo',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 2x06 (Érase un rastrillo) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '2x07-erase-una-huelga',
        static::FIELD_TITLE => '2x07 | Érase una huelga',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 2x07 (Érase una huelga) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/2/capitulos/2x07-erase-una-huelga',
        static::FIELD_OG_TITLE => '2x07 | Érase una huelga',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/2x07.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/2/capitulos/2x07-erase-una-huelga',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 2x07 (Érase una huelga) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '2x08-erase-un-piso-en-venta',
        static::FIELD_TITLE => '2x08 | Érase un piso en venta',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 2x08 (Érase un piso en venta) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/2/capitulos/2x08-erase-un-piso-en-venta',
        static::FIELD_OG_TITLE => '2x08 | Érase un piso en venta',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/2x08.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/2/capitulos/2x08-erase-un-piso-en-venta',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 2x08 (Érase un piso en venta) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '2x09-erase-una-parabolica',
        static::FIELD_TITLE => '2x09 | Érase una parabólica',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 2x09 (Érase una parabólica) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/2/capitulos/2x09-erase-una-parabolica',
        static::FIELD_OG_TITLE => '2x09 | Érase una parabólica',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/2x09.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/2/capitulos/2x09-erase-una-parabolica',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 2x09 (Érase una parabólica) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => '2x10-erase-un-video-casero',
        static::FIELD_TITLE => '2x10 | Érase un vídeo casero',
        static::FIELD_DESCRIPTION => 'Ficha con los detalles del capítulo 2x10 (Érase un vídeo casero) de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/2/capitulos/2x10-erase-un-video-casero',
        static::FIELD_OG_TITLE => '2x10 | Érase un vídeo casero',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/chapters/2x10.jpg',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/2/capitulos/2x10-erase-un-video-casero',
        static::FIELD_OG_DESCRIPTION => 'Ficha con los detalles del capítulo 2x10 (Érase un vídeo casero) de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'season-3-chapters',
        static::FIELD_TITLE => 'Temporada 3 | Capítulos',
        static::FIELD_DESCRIPTION => 'Galería con todos los capítulos de la tercera temporada de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/3',
        static::FIELD_OG_TITLE => 'Temporada 3 | Capítulos',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/logo.png',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/3',
        static::FIELD_OG_DESCRIPTION => 'Galería con todos los capítulos de la tercera temporada de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'season-4-chapters',
        static::FIELD_TITLE => 'Temporada 4 | Capítulos',
        static::FIELD_DESCRIPTION => 'Galería con todos los capítulos de la cuarta temporada de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/4',
        static::FIELD_OG_TITLE => 'Temporada 4 | Capítulos',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/logo.png',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/4',
        static::FIELD_OG_DESCRIPTION => 'Galería con todos los capítulos de la cuarta temporada de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ], [
        static::FIELD_SLUG => 'season-5-chapters',
        static::FIELD_TITLE => 'Temporada 5 | Capítulos',
        static::FIELD_DESCRIPTION => 'Galería con todos los capítulos de la quinta y última temporada de Aquí No Hay Quien Viva.',
        static::FIELD_CANONICAL_URL => 'http://anhqv-stats.es/temporadas/5',
        static::FIELD_OG_TITLE => 'Temporada 5 | Capítulos',
        static::FIELD_OG_TYPE => static::VALUE_OG_TYPE,
        static::FIELD_OG_IMAGE => 'http://anhqv-stats.es/images/logo.png',
        static::FIELD_OG_URL => 'http://anhqv-stats.es/temporadas/5',
        static::FIELD_OG_DESCRIPTION => 'Galería con todos los capítulos de la quinta y última temporada de Aquí No Hay Quien Viva.',
        static::FIELD_TWITTER_CARD => static::VALUE_TWITTER_CARD,
        static::FIELD_TWITTER_SITE => static::VALUE_TWITTER_SITE,
      ]
    ];
  }
}
